name: Bug Report
description: Report an Issue or Bug with the Multi Calendar
title: "[Bug]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        We're sorry to hear you have a problem. Can you help us solve it by providing the following details.
  - type: textarea
    id: what-happened
    attributes:
      label: What Happened
      description: What did you expect to happen?
      placeholder: When I convert a date from Gregorian to Jalali, I get an incorrect result
    validations:
      required: true
  - type: textarea
    id: how-to-reproduce
    attributes:
      label: How to Reproduce
      description: How did this occur, please add any command or code used and provide a set of reliable steps if possible.
      placeholder: |
        ./bin/date-converter.sh "2025-12-20" --to jalali
        Or using PHP:
        $converter = CalendarConverterFactory::make('jalali');
        $result = $converter->fromGregorian(2025, 12, 20);
    validations:
      required: true
  - type: input
    id: expected-output
    attributes:
      label: Expected Output
      description: What output did you expect to receive?
      placeholder: 1404/09/29
    validations:
      required: true
  - type: input
    id: actual-output
    attributes:
      label: Actual Output
      description: What output did you actually receive?
      placeholder: 1404/09/30
    validations:
      required: true
  - type: input
    id: package-version
    attributes:
      label: Package Version
      description: What version of Multi Calendar are you running? Please be as specific as possible
      placeholder: 1.0.0
    validations:
      required: true
