name: Feature Request
description: Suggest a new feature for Multi Calendar
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for suggesting a new feature! Please provide the following details to help us understand your request.
  - type: textarea
    id: feature-description
    attributes:
      label: Feature Description
      description: A clear and concise description of the feature you want to add.
      placeholder: Add support for converting dates to a new calendar system
    validations:
      required: true
  - type: textarea
    id: problem-need
    attributes:
      label: Problem/Need
      description: What problem does this feature solve or what need does it address?
      placeholder: This feature would help users convert dates to calendars that are not currently supported
    validations:
      required: true
  - type: textarea
    id: proposed-solution
    attributes:
      label: Proposed Solution
      description: How do you think this feature should work?
      placeholder: |
        Add a new converter class that implements CalendarConverterInterface
        Example usage:
        ./bin/date-converter.sh "2025-12-20" --to new-calendar
    validations:
      required: true
